name: LoginMessagePlugin
main: com.nyandayo.LoginMessagePlugin
version: 1.0-SNAPSHOT
commands:
    setmessage:
        description: This is a command to register a message.
        usage: /setmessage [message]
        permission: loginmessageplugin.setmessage
        permission-message: You don't have <permission>
    clearmessage:
        description: This is a command to clear a message.
        usage: /clearmessage
        permission: loginmessageplugin.clearmessage
        permission-message: You don't have <permission>
    showmessage:
        description: This is a command to show a message.
        usage: /showmessage
        permission: loginmessageplugin.showmessage
        permission-message: You don't have <permission>
